/*
Author: Siri S.
Company: Synergix Labs
Created: 13th April 2026
Last Modified: 13th April 2026
Tags: 
Description: Detect potential abuse of Microsoft DevTunnel
Product URL: https://www.synergix.com/LEDR
*/

AppEvents
| where Properties.Image endswith "winget.exe" 
     or Properties.CommandLine contains_cs "winget"
     or Properties.Image contains "devtunnel.exe"
| project TimeGenerated, AppRoleInstance, Properties.Image, Properties.CommandLine, Properties.ParentImage
